### ISSUE TITLE
cannot compile on fedora 25

### ISSUE THREAD

**Issue by cpg** [amahi/amahi-anywhere-fs#13]
i cannot seem to be able to build this client on 
```
$ make build-production
go get -tags "fedora linux" fs
# github.com/go-sql-driver/mysql
src/github.com/go-sql-driver/mysql/connection.go:485: undefined: driver.TxOptions
src/github.com/go-sql-driver/mysql/connection.go:491: undefined: sql.IsolationLevel
src/github.com/go-sql-driver/mysql/connection.go:491: undefined: sql.LevelDefault
src/github.com/go-sql-driver/mysql/connection.go:505: undefined: driver.NamedValue
src/github.com/go-sql-driver/mysql/connection.go:524: undefined: driver.NamedValue
src/github.com/go-sql-driver/mysql/connection.go:558: undefined: driver.NamedValue
src/github.com/go-sql-driver/mysql/connection.go:577: undefined: driver.NamedValue
src/github.com/go-sql-driver/mysql/connection.go:642: undefined: driver.NamedValue
src/github.com/go-sql-driver/mysql/utils.go:730: undefined: driver.NamedValue
src/github.com/go-sql-driver/mysql/utils.go:742: undefined: driver.IsolationLevel
src/github.com/go-sql-driver/mysql/connection.go:491: too many errors
Makefile:16: recipe for target 'build-production' failed
make: *** [build-production] Error 2
$ go version
go version go1.7.6 linux/amd64
```

**Comment by csoni111** [comment]
@cpg could you try this https://github.com/go-sql-driver/mysql/issues/638#issuecomment-316270431 ? Let me know if this helps.

**Comment by csoni111** [comment]
Oh! turns out go 1.7 is not supported (https://github.com/go-sql-driver/mysql/issues/831#issuecomment-403451499) for mysql driver.
You need to update golang to a newer version on your system.

**Comment by cpg** [comment]
that's the latest in f25. 

or compile in f27 and release it in f25, hoping it will work (and if not, piss off many of our users).

**Comment by csoni111** [comment]
Don't install go using yum or dnf, instead manually download the latest compiled tar.gz for linux from https://golang.org/dl/ , unzip and place it into `/usr/local`. Finally update the PATH variable to access from anywhere. 
[ref.](https://tecadmin.net/install-go-on-centos/)

**Comment by csoni111** [comment]
@cpg this can be closed if resolved.
